Fixes
- removed duplicated menu (no idea how that got there)
- moved the new migrator into the proper `if` clause
- added a `sed` command to fix the migrated Profile entry

diff --git a/activityfirefox b/activityfirefox
--- a/activityfirefox
+++ b/activityfirefox
@@ -18,7 +18,6 @@ set +f	# enable wildcard expansion if disabled
 if [ "$1" == "-x" ];then
 	set -x
 fi
-	COPY_TYPE=$(${KDIALOG} --menu "Select new profile type:" new "New profile (0MB)" minimal "Minimal copy (< 3MB)" templ "Template profile copy (${TPL_PROF_SIZE})" full "Full copy (${DEF_PROF_SIZE})" old "Migrate from pre-0.3 profile (${OLD_PROF_SIZE})" noop "__________________________________" help "[Help me decide]")
 
 function f_GenHelp()
 {
@@ -158,18 +157,6 @@ FF_SYNC_NAME="${ACTIVITY_NAME} @ ${HOSTNAME}"
 ACTIVITY_PROFILEDIR="${ACTIVITY_NAME_CURATED}_${ACTIVITY_UUID}"
 echo ">>> ${ACTIVITY_NAME_CURATED}"
 
-## Old profile from 0.1 and 0.2 versions of this script
-OLD_PROF="${FF_FOLDER}/????????.${ACTIVITY_UUID}"
-if [ ! -d ${OLD_PROF} ]; then
-	OLD_PROF="${FF_FOLDER}/????????.default"
-	if [ ! -d ${OLD_PROF} ]; then
-		echo ">>> Could not locate an old (pre-0.3) profile"
-		${KDIALOG} --error "Could not locate an old (pre-0.3) profile in ${FF_FOLDER} directory"
-		exit 1
-	fi
-fi
-OLD_PROF_SIZE="$(du -hs ${OLD_PROF} | cut -f1)B"
-
 ## Default profile
 DEF_PROF="${FF_FOLDER}/????????.default-release"
 if [ ! -d ${DEF_PROF} ]; then
@@ -218,8 +205,20 @@ else
 		${KDIALOG} --msgbox "Copied all from a default profile."
 	# rename old (0.1 or 0.2) profile to the new naming schema
 	elif [ "${COPY_TYPE}" = "old" ]; then
+	## Old profile from 0.1 and 0.2 versions of this script
+		OLD_PROF="${FF_FOLDER}/????????.${ACTIVITY_UUID}"
+		OLD_PROF_SIZE="$(du -hs ${OLD_PROF} | cut -f1)B"
+		if [ ! -d ${OLD_PROF} ]; then
+			OLD_PROF="${FF_FOLDER}/????????.default"
+			if [ ! -d ${OLD_PROF} ]; then
+				echo ">>> Could not locate an old (pre-0.3) profile"
+				${KDIALOG} --error "Could not locate an old (pre-0.3) profile in ${FF_FOLDER} directory"
+				exit 1
+			fi
+		fi
 		${KDIALOG} --title "Migration in progress" --passivepopup "Moving data to the new profile" 30
 		mv ${OLD_PROF} ${NEW_PROF}
+		sed 's/'${OLD_PROF}'/'${NEW_PROF}'/' "${FF_FOLDER}/"profiles.ini
 		f_FSyncPrepare
 		echo ">>> Migrated all from this Activity’s old profile"
 		${KDIALOG} --msgbox "Migrated all from this Activity’s old profile."
